NC_DIR :=inc#include for headers
BIN_DIR :=bin# *.exe
CC := gcc
CFLAGS := -g -Wall -std=c99 -pedantic -I $(INC_DIR) # compiler
flags
LFLAG := -g # linker flag
TARGET := $(BIN_DIR)/main.exe #$(SCR_DIR)/main.exe
OBJS := main.o other.o
RM := -rm -f
.PHONY: all clean check-shell
all: $(TARGET)
$(TARGET): $(OBJS) | $(BIN_DIR) #order-only prerequisite
$(CC) $(LFLAG) $(OBJS) -o $(TARGET)
main.o: main.c
$(CC) $(CFLAGS) -c main.c -o main.o
other.o: $(INC_DIR)/other.h other.c
$(CC) $(CFLAGS) -c other.c -o other.o
$(BIN_DIR):
mkdir $(BIN_DIR)
clean:
$(RM) $(OBJS)
